$ANSIBLE_VAULT;1.1;AES256
31396562376532623335663637653436323235353835323131333539366432643837313433323965
3664633361643939656665353366303732616537343638370a373439303938353233646461636439
37336134653963333636613433383662386636333238653935643161366563616166643062343461
6264646536646638610a313164356331616162663138666436626563333438393535333038653462
62393236343938646635336430623265393539336330623436643562323833316566366337366365
33653536393439346139653131643532383234633930393665316330343964383339393939663862
63653864383861303634333134333166303862653466383862333736653938623738353565316335
63326666353232353666333761353264333634633065653437366464393166316637666238366233
31636439623063616263343665393933376338316331333665303863616437356165356331653830
30356165646664653239396563323033363431326161373861313838306532653733636561363630
35386136343631613938656437313435333866646332623736666637303837346332346136343630
63383432626535376336363465616365336563343962313134383665313935373637383039353539
33653538633165633665646239633935346162363862653435653263383031626439303462323730
32646337333133393935343965326531373561623962636533633537376430653839616430346437
61313263633832306562666165386537383638663066646663336464663134336634366164303137
62333732643236393434636533383630303064613834646539393135373930346165306639366132
61343563373232646535616531653061333161396636373362353562626663643165396436376333
66313465333833393338366535353733633733663466326262663637313431363935663933663638
32313430663835616537383133336138656463363833613365633139366337373064653036643035
38633738343131336366636635376662363162326639386635646133313961386632646630666132
30356632333139623035613230313837363933383961376332633034666438343835356665343035
31326364643861346233326261313735383535666430383163613734653337613165303135303366
623664653239336466393264623666623834
